ALTER TABLE lessons ADD COLUMN consent_recorded INTEGER NOT NULL DEFAULT 0;
ALTER TABLE lessons ADD COLUMN target TEXT NOT NULL DEFAULT '';
ALTER TABLE lessons ADD COLUMN stt_model TEXT NOT NULL DEFAULT '';
ALTER TABLE lessons ADD COLUMN analyzer_model TEXT NOT NULL DEFAULT '';
ALTER TABLE lessons ADD COLUMN retention_policy TEXT NOT NULL DEFAULT '';
ALTER TABLE lessons ADD COLUMN final_cost REAL NOT NULL DEFAULT 0;
