// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ConfirmCandidate(arg1:string):Promise<main.AppSnapshot>;

export function EditCandidate(arg1:string,arg2:main.CandidateEditPatch):Promise<main.AppSnapshot>;

export function GetAppSnapshot():Promise<main.AppSnapshot>;

export function MarkMoment():Promise<main.AppSnapshot>;

export function MergeCandidates(arg1:string,arg2:string):Promise<main.AppSnapshot>;

export function Refresh():Promise<main.AppSnapshot>;

export function RejectCandidate(arg1:string):Promise<main.AppSnapshot>;

export function RequestCapturePermission():Promise<main.AppSnapshot>;

export function SaveSettings(arg1:main.SettingsPatch):Promise<main.AppSnapshot>;

export function StartLesson(arg1:main.StartLessonInput):Promise<main.AppSnapshot>;

export function StopLesson():Promise<main.AppSnapshot>;
