// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfirmCandidate(arg1) {
  return window['go']['main']['App']['ConfirmCandidate'](arg1);
}

export function DeleteLastLesson() {
  return window['go']['main']['App']['DeleteLastLesson']();
}

export function EditCandidate(arg1, arg2) {
  return window['go']['main']['App']['EditCandidate'](arg1, arg2);
}

export function GetAppSnapshot() {
  return window['go']['main']['App']['GetAppSnapshot']();
}

export function MarkMoment() {
  return window['go']['main']['App']['MarkMoment']();
}

export function MergeCandidates(arg1, arg2) {
  return window['go']['main']['App']['MergeCandidates'](arg1, arg2);
}

export function Refresh() {
  return window['go']['main']['App']['Refresh']();
}

export function RejectCandidate(arg1) {
  return window['go']['main']['App']['RejectCandidate'](arg1);
}

export function RequestCapturePermission() {
  return window['go']['main']['App']['RequestCapturePermission']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function StartLesson(arg1) {
  return window['go']['main']['App']['StartLesson'](arg1);
}

export function StopLesson() {
  return window['go']['main']['App']['StopLesson']();
}
